### ISSUE TITLE
vboxdrv: version magic '3.14.0 SMP mod_unload ' should be '3.14.0 SMP preempt mod_unload '

### ISSUE THREAD

**Issue by nigelhealy** [divx118/crouton-packages#36]
This is a resurgenc of a problem which was fixed weeks ago. Modprobe fails. Even if use --force.

You updated the headers then so need to do it again? You said 

> I just updated the kernel headers for 3.14.0 with CONFIG_PREEMPT disabled

vboxdrv: version magic '3.14.0 SMP mod_unload ' should be '3.14.0 SMP preempt mod_unload '

```
 sudo modprobe vboxdrv 
modprobe: ERROR: could not insert 'vboxdrv': Exec format error
(trusty)nigel@localhost:~$ sudo modprobe --force vboxdrv
modprobe: ERROR: could not insert 'vboxdrv': Exec format error



[25831.832662] Chromium OS LSM: init_module locking-ignored obj="/lib/modules/3.14.0/updates/dkms/vboxdrv.ko" pid=21598 cmdline="/sbin/modprobe vboxdrv"
[25831.833189] vboxdrv: version magic '3.14.0 SMP mod_unload ' should be '3.14.0 SMP preempt mod_unload '
[25857.123412] Chromium OS LSM: init_module locking-ignored obj="/lib/modules/3.14.0/updates/dkms/vboxdrv.ko" pid=21647 cmdline="modprobe vboxdrv"
[25857.123714] vboxdrv: version magic '3.14.0 SMP mod_unload ' should be '3.14.0 SMP preempt mod_unload '
[25862.874577] Chromium OS LSM: init_module locking-ignored obj="/lib/modules/3.14.0/updates/dkms/vboxdrv.ko" pid=21689 cmdline="modprobe --force vboxdrv"

```

**Comment by divx118** [comment]
@nigelhealy Yep, looks like we need to build new modules with CONFIG_PREEMPT enabled now. Thanks for reporting I will update them this week.

**Comment by divx118** [comment]
@nigelhealy 
Sorry for being a bit late, but headers are updated https://github.com/divx118/crouton-packages/commit/c621867a48a2b8613998fdb08dcc7c40486e075c Let me know if there are any problems.

**Comment by jehartzog** [comment]
Thank you for updating them! I am running 3.14 and the install was failing for me last week, is working now. Now I have VirtualBox up and running on my chromebook, thanks again!

**Comment by nigelhealy** [comment]
It's working.

I appreciate @divx118 effort on maintaining but I'd like to be able to fix these problems for myself faster, because Chromebook decides when it will update and break Virtualbox, and to wait a week can be an issue sometimes. 

Is the howto guide upto date and includes how you edit to have CONFIG_PREEMPT enabled? I could guess edit some configuration file.

**Comment by divx118** [comment]
@nigelhealy The guide is up to date. No config changed the last time, because  CONFIG_PREEMPT  is enabled by default in the chromeos kernel config. The problem was the last time that the installed kernel is always behind the branch of your kernel. Normally this is no big deal only in cases when they change/add a config that influences the kernel behavior. Such as the enabling of the CONFIG_PREEMPT Just try the guide and if you have any issues just create a ticket here and I will try to help you. You don't need it to build on your chromebook any pc/notebook with linux will do. I build the headers on my i7 12Gb ram with SSD it is a lot faster to build on that instead of my chromebook. 
BTW in the guide it says to edit the baseconfig and set CONFIG_ERROR_ON_WARNING=n this is not needed for the 3.14.0 kernel just ignore that. For the rest it is pretty straight forward.

**Comment by seedifferently** [comment]
@divx118 thank you for continuing to support this project. The latest revision worked for me on my Chromebook Pixel 2.

**Comment by divx118** [comment]
Thanks all for reporting back.
