### ISSUE TITLE
Dpkg-query error 

### ISSUE THREAD

**Issue by AilunP** [divx118/crouton-packages#60]
Hi,

I've installed the kernel header and image which were created using the guide 'Build Kernel headers and install virtualbox'. 

I then tried installing virtualbox using the command line but failed with the message below saying 'no path found matching pattern /lib/modules/3.18.0-13436-g8b496ef/kernel.

Done.
dpkg-query: no path found matching pattern /lib/modules/3.18.0-13436-g8b496ef/kernel
vboxdrv.sh: failed: Look at /var/log/vbox-install.log to find out what went wrong.
dpkg-query: no path found matching pattern /lib/modules/3.18.0-13436-g8b496ef/kernel
This system is not currently set up to build kernel modules (system extensions).
Running the following commands should set the system up correctly:

Your advice would be appreciated. 

Thanks

**Comment by divx118** [comment]
Sorry, this repo is currently broken. See https://github.com/divx118/crouton-packages/issues/45 Also it will be a pain if that is fixed to keep the kernel headers up to date for 3.18.0 since they now use a subversion which is changed on every chrome update. To get the right subversion is also not that easy.

**Comment by AilunP** [comment]
Ok thanks for the advice.
