### ISSUE TITLE
Kernel Branches and Git Version

### ISSUE THREAD

**Issue by rmartin16** [divx118/crouton-packages#71]
After many hours, I think I figured out why I couldn't get the correct kernel headers built to install virtualbox.

As documented somewhere, chromeos now uses git version as part of the kernel name. As long as I searched the kernel branches, I couldn't find a match for my uname -r.

As much as I searched through the kernel branches, my uname -r was something like 3.18.0-17554-g9194949d4df2, while every time I ran make kernelrelease, I saw something like 3.18.0-17554-XXXXXXXX. Just not enough characters at the end. My loose understanding suggests the XXXXXXXX is some git hash.

Eventually, I tried the whole process on a Ubuntu VM....and what did I see...the full "3.18.0-17554-g9194949d4df2" from make kernelrelease I was looking for....arg.

Initially, I installed git in my chroot using apt (under xenial). However, once I added ppa:git-core/ppa as a repository, I was able to install a newer version of git and alas, I got the output from make kernelrelease I was looking for: 3.18.0-17554-g9194949d4df2.

Does this mean we need to recommend a (minimum) certain version of git given the changes to Google's creation of chromeos kernel branches?

Also, can the whole process of manually searching the branch commits be circumvented with "git checkout 00000-xxxxxxxxxxxx" with "00000-xxxxxxxxxxxx" coming from chromeos-3.18.0-00000-xxxxxxxxxxxx, for instance? (source: https://github.com/dnschneid/crouton/wiki/Build-chrome-os-kernel-and-kernel-modules)

Thanks.

**Comment by divx118** [comment]
@rmartin16 thanks for the info, maybe someone can use it. I didn't look at building the kernel headers for a long time. It isn't something as easy as doing a git checkout to find the right git hash for your kernel. Also you need to do this process almost every time chromeos updates, because there is almost always a new kernel release. So I just use galliumos next to chromeos and crouton. I just reboot into galliumos if I need to use some windows only app. Or if I need some other linux progs which need specific kernel modules.

**Comment by rmartin16** [comment]
Gotcha. I'll drop a quick line in the wiki and check out galliumos. Thanks for the info.
